# Generated by Django 4.1 on 2022-08-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=50)),
                ('todo_status_1', models.BooleanField(default=False)),
                ('todo_status_2', models.BooleanField(default=False)),
                ('todo_status_3', models.BooleanField(default=False)),
                ('todo_status_4', models.BooleanField(default=False)),
                ('todo_status_5', models.BooleanField(default=False)),
                ('todo_status_6', models.BooleanField(default=False)),
                ('todo_status_7', models.BooleanField(default=False)),
                ('todo_status_8', models.BooleanField(default=False)),
                ('todo_status_9', models.BooleanField(default=False)),
                ('todo_status_10', models.BooleanField(default=False)),
                ('todo_status_11', models.BooleanField(default=False)),
                ('todo_status_12', models.BooleanField(default=False)),
                ('todo_status_13', models.BooleanField(default=False)),
                ('todo_status_14', models.BooleanField(default=False)),
                ('todo_status_15', models.BooleanField(default=False)),
                ('todo_status_16', models.BooleanField(default=False)),
                ('todo_status_17', models.BooleanField(default=False)),
                ('todo_status_18', models.BooleanField(default=False)),
                ('todo_status_19', models.BooleanField(default=False)),
                ('todo_status_20', models.BooleanField(default=False)),
                ('todo_status_21', models.BooleanField(default=False)),
                ('todo_status_22', models.BooleanField(default=False)),
                ('todo_status_23', models.BooleanField(default=False)),
                ('todo_status_24', models.BooleanField(default=False)),
                ('todo_status_25', models.BooleanField(default=False)),
            ],
        ),
    ]
