# Generated by Django 4.1 on 2022-08-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='todo_1',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_10',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_11',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_12',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_13',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_14',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_15',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_16',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_17',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_18',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_19',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_2',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_20',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_21',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_22',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_23',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_24',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_25',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_3',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_4',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_5',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_6',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_7',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_8',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='todo_list',
            name='todo_9',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_11',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_12',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_13',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_14',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_15',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_16',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_17',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_18',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_19',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_20',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_21',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_22',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_23',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_24',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_25',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_6',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_7',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_8',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='todo_status_9',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
