# Generated by Django 4.1 on 2022-08-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_list_todo_1_todo_list_todo_10_todo_list_todo_11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todo_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField()),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo_category')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo_list',
        ),
    ]
