# Generated by Django 4.1 on 2022-08-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_category_todo_item_delete_todo_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo_Category',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Todo_Item',
            new_name='Todo',
        ),
    ]
