# Generated by Django 4.1 on 2022-08-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_todo_1_todo_todo_2_todo_todo_3_todo_todo_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_1',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_2',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_3',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_4',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_5',
        ),
    ]
